### ISSUE TITLE
typo in the paper?

### ISSUE THREAD

**Issue by alanz** [jyp/prettiest#1]
Your draft paper at http://jyp.github.io/pdf/Prettiest.pdf says on page 3

"
It does not look too bad — but there is a spurious line break after
the atom `abcdefgh`
"

I suspect it should be 'abcde', referring to the first one, which now has a spurious line break.

And the email address in the paper bounces.

**Comment by jyp** [comment]
Thanks; this error has been pointed out by several reviewers :)
I'll update the paper draft today.
