### ISSUE TITLE
Annotated variant

### ISSUE THREAD

**Issue by phadej** [jyp/prettiest#2]
Like the in `pretty` http://hackage.haskell.org/package/pretty-1.1.3.5/docs/Text-PrettyPrint-Annotated.html

Would that be in scope of this library.

I like the (so far?) prettiest layout, but would like to have colors there, so annotated `Doc` is a must.

**Comment by jyp** [comment]
I suppose that it would not be too difficult to support annotations. This is not a priority for me though. I'll merge a good PR but won't work on it myself.

**Comment by jyp** [comment]
Fixed by PR
